/**
 * Achievement Definitions
 *
 * All achievements that can be unlocked in wit.
 * These are inserted into the database on first run.
 */

import { type AchievementCategory, type AchievementRarity } from './gamification';

export interface AchievementDefinition {
  key: string;
  name: string;
  description: string;
  category: AchievementCategory;
  rarity: AchievementRarity;
  xpReward: number;
  icon: string;
  isSecret: boolean;
  displayOrder: number;
}

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // ============ COMMITS ============
  {
    key: 'first_commit',
    name: 'First Steps',
    description: 'Make your first commit',
    category: 'commits',
    rarity: 'common',
    xpReward: 50,
    icon: '🚀',
    isSecret: false,
    displayOrder: 1,
  },
  {
    key: 'commits_10',
    name: 'Getting Started',
    description: 'Make 10 commits',
    category: 'commits',
    rarity: 'common',
    xpReward: 100,
    icon: '📝',
    isSecret: false,
    displayOrder: 2,
  },
  {
    key: 'commits_100',
    name: 'Committed Developer',
    description: 'Make 100 commits',
    category: 'commits',
    rarity: 'uncommon',
    xpReward: 250,
    icon: '💪',
    isSecret: false,
    displayOrder: 3,
  },
  {
    key: 'commits_500',
    name: 'Code Machine',
    description: 'Make 500 commits',
    category: 'commits',
    rarity: 'rare',
    xpReward: 500,
    icon: '🤖',
    isSecret: false,
    displayOrder: 4,
  },
  {
    key: 'commits_1000',
    name: 'Thousand Lines',
    description: 'Make 1,000 commits',
    category: 'commits',
    rarity: 'epic',
    xpReward: 1000,
    icon: '🏆',
    isSecret: false,
    displayOrder: 5,
  },
  {
    key: 'commits_5000',
    name: 'Code Legend',
    description: 'Make 5,000 commits',
    category: 'commits',
    rarity: 'legendary',
    xpReward: 2500,
    icon: '👑',
    isSecret: false,
    displayOrder: 6,
  },

  // ============ PULL REQUESTS ============
  {
    key: 'first_pr',
    name: 'Pull Request Pioneer',
    description: 'Open your first pull request',
    category: 'pull_requests',
    rarity: 'common',
    xpReward: 75,
    icon: '🔀',
    isSecret: false,
    displayOrder: 10,
  },
  {
    key: 'first_pr_merged',
    name: 'Merger',
    description: 'Get your first pull request merged',
    category: 'pull_requests',
    rarity: 'common',
    xpReward: 100,
    icon: '✅',
    isSecret: false,
    displayOrder: 11,
  },
  {
    key: 'prs_merged_10',
    name: 'Serial Merger',
    description: 'Get 10 pull requests merged',
    category: 'pull_requests',
    rarity: 'uncommon',
    xpReward: 300,
    icon: '🔄',
    isSecret: false,
    displayOrder: 12,
  },
  {
    key: 'prs_merged_50',
    name: 'Merge Master',
    description: 'Get 50 pull requests merged',
    category: 'pull_requests',
    rarity: 'rare',
    xpReward: 750,
    icon: '🎯',
    isSecret: false,
    displayOrder: 13,
  },
  {
    key: 'prs_merged_100',
    name: 'PR Pro',
    description: 'Get 100 pull requests merged',
    category: 'pull_requests',
    rarity: 'epic',
    xpReward: 1500,
    icon: '⭐',
    isSecret: false,
    displayOrder: 14,
  },
  {
    key: 'prs_merged_500',
    name: 'Merge Legend',
    description: 'Get 500 pull requests merged',
    category: 'pull_requests',
    rarity: 'legendary',
    xpReward: 3000,
    icon: '🌟',
    isSecret: false,
    displayOrder: 15,
  },

  // ============ REVIEWS ============
  {
    key: 'first_review',
    name: 'Code Reviewer',
    description: 'Submit your first code review',
    category: 'reviews',
    rarity: 'common',
    xpReward: 50,
    icon: '👀',
    isSecret: false,
    displayOrder: 20,
  },
  {
    key: 'reviews_10',
    name: 'Helpful Reviewer',
    description: 'Submit 10 code reviews',
    category: 'reviews',
    rarity: 'uncommon',
    xpReward: 200,
    icon: '🔍',
    isSecret: false,
    displayOrder: 21,
  },
  {
    key: 'reviews_50',
    name: 'Review Champion',
    description: 'Submit 50 code reviews',
    category: 'reviews',
    rarity: 'rare',
    xpReward: 500,
    icon: '🏅',
    isSecret: false,
    displayOrder: 22,
  },
  {
    key: 'reviews_100',
    name: 'Quality Guardian',
    description: 'Submit 100 code reviews',
    category: 'reviews',
    rarity: 'epic',
    xpReward: 1000,
    icon: '🛡️',
    isSecret: false,
    displayOrder: 23,
  },
  {
    key: 'reviews_500',
    name: 'Grand Reviewer',
    description: 'Submit 500 code reviews',
    category: 'reviews',
    rarity: 'legendary',
    xpReward: 2500,
    icon: '📜',
    isSecret: false,
    displayOrder: 24,
  },

  // ============ ISSUES ============
  {
    key: 'first_issue',
    name: 'Bug Hunter',
    description: 'Open your first issue',
    category: 'issues',
    rarity: 'common',
    xpReward: 50,
    icon: '🐛',
    isSecret: false,
    displayOrder: 30,
  },
  {
    key: 'issues_10',
    name: 'Issue Tracker',
    description: 'Open 10 issues',
    category: 'issues',
    rarity: 'uncommon',
    xpReward: 150,
    icon: '📋',
    isSecret: false,
    displayOrder: 31,
  },
  {
    key: 'issues_closed_10',
    name: 'Problem Solver',
    description: 'Close 10 issues',
    category: 'issues',
    rarity: 'uncommon',
    xpReward: 200,
    icon: '🔧',
    isSecret: false,
    displayOrder: 32,
  },
  {
    key: 'issues_closed_50',
    name: 'Bug Exterminator',
    description: 'Close 50 issues',
    category: 'issues',
    rarity: 'rare',
    xpReward: 500,
    icon: '🎯',
    isSecret: false,
    displayOrder: 33,
  },
  {
    key: 'issues_closed_100',
    name: 'Issue Master',
    description: 'Close 100 issues',
    category: 'issues',
    rarity: 'epic',
    xpReward: 1000,
    icon: '💎',
    isSecret: false,
    displayOrder: 34,
  },

  // ============ COLLABORATION ============
  {
    key: 'first_comment',
    name: 'Conversationalist',
    description: 'Leave your first comment',
    category: 'collaboration',
    rarity: 'common',
    xpReward: 25,
    icon: '💬',
    isSecret: false,
    displayOrder: 40,
  },
  {
    key: 'comments_100',
    name: 'Active Discusser',
    description: 'Leave 100 comments',
    category: 'collaboration',
    rarity: 'uncommon',
    xpReward: 300,
    icon: '🗣️',
    isSecret: false,
    displayOrder: 41,
  },
  {
    key: 'first_repo',
    name: 'Repository Creator',
    description: 'Create your first repository',
    category: 'collaboration',
    rarity: 'common',
    xpReward: 75,
    icon: '📁',
    isSecret: false,
    displayOrder: 42,
  },
  {
    key: 'repos_10',
    name: 'Prolific Creator',
    description: 'Create 10 repositories',
    category: 'collaboration',
    rarity: 'rare',
    xpReward: 500,
    icon: '🏗️',
    isSecret: false,
    displayOrder: 43,
  },
  {
    key: 'first_star_received',
    name: 'Rising Star',
    description: 'Receive your first star on a repository',
    category: 'collaboration',
    rarity: 'uncommon',
    xpReward: 100,
    icon: '⭐',
    isSecret: false,
    displayOrder: 44,
  },
  {
    key: 'stars_received_100',
    name: 'Star Collector',
    description: 'Receive 100 stars across all repositories',
    category: 'collaboration',
    rarity: 'epic',
    xpReward: 1500,
    icon: '🌟',
    isSecret: false,
    displayOrder: 45,
  },
  {
    key: 'first_fork',
    name: 'Forker',
    description: 'Fork a repository for the first time',
    category: 'collaboration',
    rarity: 'common',
    xpReward: 50,
    icon: '🍴',
    isSecret: false,
    displayOrder: 46,
  },

  // ============ STREAKS ============
  {
    key: 'streak_7',
    name: 'Week Warrior',
    description: 'Maintain a 7-day activity streak',
    category: 'streaks',
    rarity: 'uncommon',
    xpReward: 200,
    icon: '🔥',
    isSecret: false,
    displayOrder: 50,
  },
  {
    key: 'streak_30',
    name: 'Monthly Master',
    description: 'Maintain a 30-day activity streak',
    category: 'streaks',
    rarity: 'rare',
    xpReward: 500,
    icon: '🌋',
    isSecret: false,
    displayOrder: 51,
  },
  {
    key: 'streak_90',
    name: 'Quarterly Champion',
    description: 'Maintain a 90-day activity streak',
    category: 'streaks',
    rarity: 'epic',
    xpReward: 1500,
    icon: '💥',
    isSecret: false,
    displayOrder: 52,
  },
  {
    key: 'streak_365',
    name: 'Year of Code',
    description: 'Maintain a 365-day activity streak',
    category: 'streaks',
    rarity: 'legendary',
    xpReward: 5000,
    icon: '🎆',
    isSecret: false,
    displayOrder: 53,
  },

  // ============ MILESTONES ============
  {
    key: 'level_10',
    name: 'Rising Developer',
    description: 'Reach level 10',
    category: 'milestones',
    rarity: 'uncommon',
    xpReward: 250,
    icon: '📈',
    isSecret: false,
    displayOrder: 60,
  },
  {
    key: 'level_25',
    name: 'Experienced Coder',
    description: 'Reach level 25',
    category: 'milestones',
    rarity: 'rare',
    xpReward: 750,
    icon: '🚀',
    isSecret: false,
    displayOrder: 61,
  },
  {
    key: 'level_50',
    name: 'Master Developer',
    description: 'Reach level 50',
    category: 'milestones',
    rarity: 'epic',
    xpReward: 2000,
    icon: '🎖️',
    isSecret: false,
    displayOrder: 62,
  },
  {
    key: 'level_100',
    name: 'Legendary Status',
    description: 'Reach level 100',
    category: 'milestones',
    rarity: 'legendary',
    xpReward: 10000,
    icon: '👑',
    isSecret: false,
    displayOrder: 63,
  },
  {
    key: 'first_release',
    name: 'Releaser',
    description: 'Publish your first release',
    category: 'milestones',
    rarity: 'uncommon',
    xpReward: 200,
    icon: '📦',
    isSecret: false,
    displayOrder: 64,
  },

  // ============ SPECIAL/SECRET ============
  {
    key: 'night_owl',
    name: 'Night Owl',
    description: 'Make a commit between midnight and 4 AM',
    category: 'special',
    rarity: 'uncommon',
    xpReward: 100,
    icon: '🦉',
    isSecret: true,
    displayOrder: 70,
  },
  {
    key: 'early_bird',
    name: 'Early Bird',
    description: 'Make a commit between 5 AM and 7 AM',
    category: 'special',
    rarity: 'uncommon',
    xpReward: 100,
    icon: '🐦',
    isSecret: true,
    displayOrder: 71,
  },
  {
    key: 'weekend_warrior',
    name: 'Weekend Warrior',
    description: 'Make commits on both Saturday and Sunday in the same weekend',
    category: 'special',
    rarity: 'uncommon',
    xpReward: 75,
    icon: '⚔️',
    isSecret: true,
    displayOrder: 72,
  },
  {
    key: 'new_year_commit',
    name: 'New Year Coder',
    description: 'Make a commit on January 1st',
    category: 'special',
    rarity: 'rare',
    xpReward: 250,
    icon: '🎉',
    isSecret: true,
    displayOrder: 73,
  },
  {
    key: 'halloween_commit',
    name: 'Spooky Coder',
    description: 'Make a commit on Halloween (October 31st)',
    category: 'special',
    rarity: 'rare',
    xpReward: 150,
    icon: '🎃',
    isSecret: true,
    displayOrder: 74,
  },
  {
    key: 'speedrun',
    name: 'Speedrunner',
    description: 'Open and merge a PR within 10 minutes',
    category: 'special',
    rarity: 'rare',
    xpReward: 200,
    icon: '⚡',
    isSecret: true,
    displayOrder: 75,
  },
  {
    key: 'perfectionist',
    name: 'Perfectionist',
    description: 'Get a PR approved with no requested changes',
    category: 'special',
    rarity: 'uncommon',
    xpReward: 100,
    icon: '✨',
    isSecret: false,
    displayOrder: 76,
  },
  {
    key: 'ai_native',
    name: 'AI Native',
    description: 'Use wit ai commit for 10 commits',
    category: 'special',
    rarity: 'uncommon',
    xpReward: 150,
    icon: '🤖',
    isSecret: false,
    displayOrder: 77,
  },
  {
    key: 'polyglot',
    name: 'Polyglot',
    description: 'Commit code in 5 different programming languages',
    category: 'special',
    rarity: 'rare',
    xpReward: 300,
    icon: '🌐',
    isSecret: false,
    displayOrder: 78,
  },
  {
    key: 'community_contributor',
    name: 'Community Contributor',
    description: 'Get a PR merged in a repository you don\'t own',
    category: 'special',
    rarity: 'uncommon',
    xpReward: 200,
    icon: '🤝',
    isSecret: false,
    displayOrder: 79,
  },
];

/**
 * Get achievement thresholds for a specific stat
 */
export function getAchievementThresholds(statType: string): number[] {
  const thresholds: Record<string, number[]> = {
    commits: [1, 10, 100, 500, 1000, 5000],
    prs_merged: [1, 10, 50, 100, 500],
    reviews: [1, 10, 50, 100, 500],
    issues_opened: [1, 10],
    issues_closed: [10, 50, 100],
    comments: [1, 100],
    streak: [7, 30, 90, 365],
    level: [10, 25, 50, 100],
  };
  
  return thresholds[statType] || [];
}

/**
 * Get achievement key for a stat milestone
 */
export function getAchievementKeyForMilestone(
  statType: string,
  value: number
): string | null {
  const keyMap: Record<string, Record<number, string>> = {
    commits: {
      1: 'first_commit',
      10: 'commits_10',
      100: 'commits_100',
      500: 'commits_500',
      1000: 'commits_1000',
      5000: 'commits_5000',
    },
    prs_opened: {
      1: 'first_pr',
    },
    prs_merged: {
      1: 'first_pr_merged',
      10: 'prs_merged_10',
      50: 'prs_merged_50',
      100: 'prs_merged_100',
      500: 'prs_merged_500',
    },
    reviews: {
      1: 'first_review',
      10: 'reviews_10',
      50: 'reviews_50',
      100: 'reviews_100',
      500: 'reviews_500',
    },
    issues_opened: {
      1: 'first_issue',
      10: 'issues_10',
    },
    issues_closed: {
      10: 'issues_closed_10',
      50: 'issues_closed_50',
      100: 'issues_closed_100',
    },
    comments: {
      1: 'first_comment',
      100: 'comments_100',
    },
    streak: {
      7: 'streak_7',
      30: 'streak_30',
      90: 'streak_90',
      365: 'streak_365',
    },
    level: {
      10: 'level_10',
      25: 'level_25',
      50: 'level_50',
      100: 'level_100',
    },
  };
  
  return keyMap[statType]?.[value] || null;
}
