/**
 * Type definitions for wit AI integration
 */

/**
 * Configuration for AI features
 */
export interface AIConfig {
  /** Model to use (e.g., 'openai/gpt-4o', 'anthropic/claude-opus-4-5') */
  model?: string;
  /** API key (defaults to environment variable based on provider) */
  apiKey?: string;
  /** Enable verbose logging */
  verbose?: boolean;
}

/**
 * Options for AI-generated commit messages
 */
export interface CommitMessageOptions {
  /** Style of commit message */
  style?: 'conventional' | 'descriptive' | 'concise';
  /** Include detailed body explaining changes */
  includeBody?: boolean;
  /** Maximum length for the subject line */
  maxSubjectLength?: number;
  /** Scope for conventional commits (e.g., 'feat', 'fix', 'docs') */
  scope?: string;
}

/**
 * Options for AI-assisted conflict resolution
 */
export interface ConflictResolutionOptions {
  /** Strategy for resolution */
  strategy?: 'ours' | 'theirs' | 'merge' | 'auto';
  /** Whether to explain the resolution */
  explain?: boolean;
  /** File path for specific file resolution */
  filePath?: string;
}

/**
 * Result of AI commit message generation
 */
export interface GeneratedCommitMessage {
  subject: string;
  body?: string;
  type?: string;
  scope?: string;
  breaking?: boolean;
}

/**
 * Result of AI conflict resolution
 */
export interface ConflictResolution {
  filePath: string;
  resolvedContent: string;
  explanation?: string;
  confidence: number;
}

/**
 * PR description generated by AI
 */
export interface GeneratedPRDescription {
  title: string;
  summary: string;
  changes: string[];
  testPlan?: string;
  breakingChanges?: string[];
}

/**
 * Code review result
 */
export interface CodeReviewResult {
  summary: string;
  issues: CodeReviewIssue[];
  suggestions: string[];
  securityConcerns: string[];
  overallScore: number;
}

export interface CodeReviewIssue {
  severity: 'info' | 'warning' | 'error';
  file: string;
  line?: number;
  message: string;
  suggestion?: string;
}

/**
 * Agent modes determine what tools and capabilities are available
 * - pm: Ask questions, create issues, PRs, manage projects
 * - code: Write/edit files, create branches, commit changes
 */
export type AgentMode = 'pm' | 'code';

/**
 * Agent mode configuration
 */
export interface AgentModeConfig {
  id: AgentMode;
  name: string;
  description: string;
  icon: string;
}

/**
 * Available agent modes
 */
export const AGENT_MODES: Record<AgentMode, AgentModeConfig> = {
  pm: {
    id: 'pm',
    name: 'PM',
    description: 'Ask questions, create issues, PRs, and manage projects',
    icon: 'clipboard-list',
  },
  code: {
    id: 'code',
    name: 'Code',
    description: 'Write code, edit files, create branches, and commit changes',
    icon: 'code',
  },
};

/**
 * Context passed to agent tools for repo-scoped operations
 */
export interface AgentContext {
  /** Repository ID from the database */
  repoId: string;
  /** Repository owner username */
  owner: string;
  /** Repository name */
  repoName: string;
  /** Path to the repository on disk (server-side) */
  repoPath: string;
  /** Current user ID */
  userId: string;
  /** Current agent mode */
  mode: AgentMode;
}
