/**
 * Type definitions for wit AI integration
 */

/**
 * Configuration for AI features
 */
export interface AIConfig {
  /** Model to use (e.g., 'openai/gpt-4o', 'anthropic/claude-sonnet-4-20250514') */
  model?: string;
  /** API key (defaults to environment variable based on provider) */
  apiKey?: string;
  /** Enable verbose logging */
  verbose?: boolean;
}

/**
 * Options for AI-generated commit messages
 */
export interface CommitMessageOptions {
  /** Style of commit message */
  style?: 'conventional' | 'descriptive' | 'concise';
  /** Include detailed body explaining changes */
  includeBody?: boolean;
  /** Maximum length for the subject line */
  maxSubjectLength?: number;
  /** Scope for conventional commits (e.g., 'feat', 'fix', 'docs') */
  scope?: string;
}

/**
 * Options for AI-assisted conflict resolution
 */
export interface ConflictResolutionOptions {
  /** Strategy for resolution */
  strategy?: 'ours' | 'theirs' | 'merge' | 'auto';
  /** Whether to explain the resolution */
  explain?: boolean;
  /** File path for specific file resolution */
  filePath?: string;
}

/**
 * Result of AI commit message generation
 */
export interface GeneratedCommitMessage {
  subject: string;
  body?: string;
  type?: string;
  scope?: string;
  breaking?: boolean;
}

/**
 * Result of AI conflict resolution
 */
export interface ConflictResolution {
  filePath: string;
  resolvedContent: string;
  explanation?: string;
  confidence: number;
}

/**
 * PR description generated by AI
 */
export interface GeneratedPRDescription {
  title: string;
  summary: string;
  changes: string[];
  testPlan?: string;
  breakingChanges?: string[];
}

/**
 * Code review result
 */
export interface CodeReviewResult {
  summary: string;
  issues: CodeReviewIssue[];
  suggestions: string[];
  securityConcerns: string[];
  overallScore: number;
}

export interface CodeReviewIssue {
  severity: 'info' | 'warning' | 'error';
  file: string;
  line?: number;
  message: string;
  suggestion?: string;
}
